#!/bin/sh
# Put a dash at the end of open to use stdin as arguments
# usage: echo "TextEdit" | open -a -
for last; do true; done
if [ "$last" == '-' ]; then
  arg=`cat`
  cmd=`echo $@ | sed -e "s/-$/${arg}/"`
  /usr/bin/open $cmd
else
  /usr/bin/open $@
fi
